# Display ascii art
print("\t       ##")
print("\t      ####")
print("\t    []#oo#[]")
print("\t      ####")
print("\t       []")
print("\t[][][][][][][][]")
print("\t    [][][][]")
print("\t    [][][][]")
print("\t    [][][][]")
